services:
  db:
    image: postgres:15
    container_name: weather_bot_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORTS}

  bot:
    build: .
    container_name: weather_bot_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/weather_db

volumes:
  postgres_data: